Update User Stories and Development Workflow guides
labzero/guides pull request #66
Opened 2022-07-21 21:29 UTC by Shiun

Update How We Write User Stories to include example.

Update Development Workflow Guide to be less rails-centric.

2022-07-21 21:35 UTC, JeffreyATW requested changes
Looks great! Some small spelling corrections.

2022-07-21 21:35 UTC, JeffreyATW commented on process/development_workflow.md
> +In most cases, all the code for a given story is contained in a single commit. (As an exception, when including an unrelated refactoring or other code change in a story, it usually makes sense to add
`s/Functional tests ensures/Functional tests ensure`

2022-07-21 21:35 UTC, JeffreyATW commented on process/development_workflow.md
> +Use code quality scanners, such as [brakeman](https://brakemanscanner.org/) to ensure new code does not introduce vulnerabilities.  Use code coverage tool, such as [simplecov](https://github.com/simp
`s/Use code coverage/Use a code coverage`

2022-07-21 21:35 UTC, JeffreyATW commented on process/development_workflow.md
> +Just because there were three or four sort-of-related things that could be done at once does not mean they should be lumped into one PR. The potential for one of the changes to block the other change
`s/And as such/As such`

2022-07-21 21:35 UTC, JeffreyATW commented on process/how_we_write_user_stories.md
> +Here's an example of a login in story.
`s/login in/login`

2022-07-21 21:35 UTC, JeffreyATW commented on process/how_we_write_user_stories.md
> +>__Scenario: User does NOT supplies correct username and password__
`s/NOT supplies/NOT supply`

2022-07-21 21:58 UTC, Shiun commented
A lot of grammar errors 🙈.  Pushing up changes now

2022-07-22 00:53 UTC, JeffreyATW requested changes

2022-07-22 00:53 UTC, JeffreyATW commented on process/development_workflow.md
> +Just because there were three or four sort-of-related things that could be done at once does not mean they should be lumped into one PR. The potential for one of the changes to block the other change
`s/try out best/try our best`

2022-07-28 18:17 UTC, JeffreyATW approved these changes

2022-07-29 20:30 UTC, merged